version: '3.4'

services:
  pwntainer:
    image: pwntainer
    container_name: pwntainer
    hostname: pwntainer
    ports:
      - 8000:8000
    build: .
    restart: unless-stopped
    volumes:
      - ./data/:/opt/pwntainer/data/
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 750M
        reservations:
          cpus: '0.10'
          memory: 250M
