version: '3'

tasks:
  simple-setup: 
    deps: [install-deps, build-svc-image, push-svc-image, bootstrap-aws, deploy-app, install-cli-src, init-app]

  test:
    cmds:
      - dotnet test
  
  build-api:
    cmds:
      - dotnet build src/pwnctl.api/pwnctl.api.csproj -c Release
  
  build-pwnctl-cli:
    cmds:
      - dotnet publish src/pwnctl.cli/pwnctl.cli.csproj -c Release
  
  build-svc:
    cmds:
      - dotnet publish src/core/pwnctl.svc/pwnctl.svc.csproj -c Release

  build-svc-image:
    cmds:
      - docker build src/core/ -t public.ecr.aws/i0m2p7r6/pwnctl:latest

  push-svc-image:
    cmds:
      - |
        region=$(aws configure get region)
        aws ecr-public get-login-password --region $region | docker login --username AWS --password-stdin public.ecr.aws/i0m2p7r6
        docker push public.ecr.aws/i0m2p7r6/pwnctl:latest
        
  build-all: 
    deps: [build-pwnctl-cli, build-api, build-svc-image]
    
  install-cli-src:
    deps: [build-pwnctl-cli]
    cmds:
      - chmod +x src/pwnctl.cli/bin/Release/net6.0/linux-x64/publish/pwnctl
      - sudo mv src/pwnctl.cli/bin/Release/net6.0/linux-x64/publish/pwnctl /usr/local/bin
      - sudo mv src/pwnctl.cli/bin/Release/net6.0/linux-x64/publish/config.ini /etc/pwnctl/
  
  bootstrap-aws:
    cmds:
      - |
        region=$(aws configure get region)
        accountId=$(aws sts get-caller-identity --query "Account" --output text)
        cdk bootstrap aws://${accountId}/${region} -o src/core/pwnctl.infra.cdk/cdk.out

  deploy-app:
    deps: [clean-cdk, build-api]
    cmds:
      - cdk deploy -o src/core/pwnctl.infra.cdk/cdk.out

  init-app:
    cmds:
      - ./init.sh

  clean-cdk:
    cmds:
      - rm -rf src/core/pwnctl.infra.cdk/cdk.out

  destroy:
    cmds:
      - cdk destroy -o src/core/pwnctl.infra.cdk/cdk.out

  install-deps:
    cmds:
      - |
        sudo apt-get install -y git curl wget jq docker nodejs
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
        unzip awscliv2.zip
        rm awscliv2.zip
        ./aws/install --update
        rm -rf ./aws
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash - 
        npm install -g aws-cdk
        curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 6.0 -Runtime aspnetcore -InstallDir /usr/share/dotnet --architecture x64
        ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
        pip install awscurl

