version: '3'

tasks:
  simple-setup:
    deps: [install-deps, build-svc-image, push-svc-image, bootstrap-aws, deploy-app, install-cli, init-app]

  test:
    cmds:
      - dotnet test --filter "FullyQualifiedName~test.unit"

  test-svc:
    cmds:
      - dotnet test --filter "FullyQualifiedName~pwnctl.svc"

  build-api:
    cmds:
      - dotnet build src/pwnctl.api/pwnctl.api.csproj -c Release

  build-cli:
    cmds:
      - dotnet publish src/pwnctl.cli/pwnctl.cli.csproj -c Release

  build-svc:
    cmds:
      - dotnet publish src/core/pwnctl.svc/pwnctl.svc.csproj -c Release

  build-svc-image:
    cmds:
      - docker build src/core/ -t public.ecr.aws/i0m2p7r6/pwnctl:latest

  push-svc-image:
    cmds:
      - |
        region=$(aws configure get region)
        aws ecr-public get-login-password --region $region \
          | docker login --username AWS --password-stdin public.ecr.aws/i0m2p7r6
        docker push public.ecr.aws/i0m2p7r6/pwnctl:latest

  build-all:
    deps: [build-cli, build-api, build-svc-image]

  install-cli:
    deps: [build-cli]
    cmds:
      - chmod +x src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/pwnctl
      - sudo mv src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/pwnctl /usr/local/bin
      - sudo mkdir -p /etc/pwnctl/
      - sudo chown $USER /etc/pwnctl/
      - sudo mv src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/config.ini /etc/pwnctl/
      - sudo ./src/core/pwnctl.svc/scripts/get-psl.sh /etc/pwnctl/
      - sudo cp -r ./src/core/pwnctl.infra/Persistence/seed /etc/pwnctl

  deploy-app:
    deps: [build-api, install-cli]
    cmds:
      - cd infra && echo yes | terraform apply
      - cd -
      - ./bin/upload-conf.sh

  debug-svc:
    cmds:
      - |
        mkdir -p deployment/seed/
        cp ./src/core/pwnctl.infra/Persistence/seed/*.yml deployment/seed/
        docker run -e PWNCTL_TEST_RUN=true -e PWNCTL_INSTALL_PATH=/mnt/efs \
                   -e PWNCTL_Logging__FilePath=/mnt/efs -e PWNCTL_Logging__MinLevel=Debug \
                   -v "$(pwd)"/deployment:/mnt/efs -t public.ecr.aws/i0m2p7r6/pwnctl:latest

  get-logs:
    cmds:
      - awslogs get -s 1440m -G --timestamp /aws/ecs/worker | tee pwnctl.log

  destroy:
    cmds:
      - cd infra && echo yes | terraform destroy
      - cd -

  install-deps:
    cmds:
      - ./bin/install-deps.sh
