version: '3'

tasks:
  test:
    deps: [test-core, test-exec, test-proc]

  test-core:
    cmds:
      - dotnet test --filter "FullyQualifiedName~test.unit"

  test-proc:
    deps: [build-proc-image]
    cmds:
      - |
        rm -rf test/pwnctl.proc.test.int/bin
        export UNTESTED_IMAGE=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-proc") | .repositoryUri'):untested_$(git rev-parse --short HEAD)
        dotnet test --filter "FullyQualifiedName~pwnctl.proc"

  test-exec:
    deps: [build-exec-long-image]
    cmds:
    - |
      rm -rf test/pwnctl.exec.test.int/bin
      export UNTESTED_IMAGE=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-long") | .repositoryUri'):untested_$(git rev-parse --short HEAD)
      dotnet test --filter "FullyQualifiedName~pwnctl.exec"

  build-api:
    cmds:
      - dotnet build src/pwnctl.api/pwnctl.api.csproj -c Release

  build-cli:
    cmds:
      - dotnet publish src/pwnctl.cli/pwnctl.cli.csproj -c Release

  build-exec-short-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-short") | .repositoryUri')
        docker buildx build --build-arg COMMIT_HASH=$commitHash --ssh default=$SSH_AUTH_SOCK src/core/ -f src/core/pwnctl.exec/shortlived/Dockerfile -t ${ecrUri}:$commitHash
        docker tag ${ecrUri}:$commitHash ${ecrUri}:untested_$commitHash

  build-exec-long-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-long") | .repositoryUri')
        docker buildx build --build-arg COMMIT_HASH=$commitHash --ssh default=$SSH_AUTH_SOCK src/core/ -f src/core/pwnctl.exec/longlived/Dockerfile -t ${ecrUri}:$commitHash
        docker tag ${ecrUri}:$commitHash ${ecrUri}:untested_$commitHash

  push-exec-short-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        region=$(aws configure get region)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-short") | .repositoryUri')
        aws ecr get-login-password --region $region \
          | docker login --username AWS --password-stdin ${ecrUri}
        docker push ${ecrUri}:$commitHash

  push-exec-long-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        region=$(aws configure get region)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-long") | .repositoryUri')
        aws ecr get-login-password --region $region \
          | docker login --username AWS --password-stdin ${ecrUri}
        docker push ${ecrUri}:$commitHash

  build-proc-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-proc") | .repositoryUri')
        docker build --build-arg COMMIT_HASH=$commitHash src/core/ -f src/core/pwnctl.proc/Dockerfile -t ${ecrUri}:$commitHash
        docker tag ${ecrUri}:$commitHash ${ecrUri}:untested_$commitHash

  push-proc-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        region=$(aws configure get region)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-proc") | .repositoryUri')
        aws ecr get-login-password --region $region \
          | docker login --username AWS --password-stdin $ecrUri
        docker push ${ecrUri}:$commitHash

  build-all:
    deps: [build-cli, build-api, build-exec-short-image, build-exec-long-image, build-proc-image]

  install-cli:
    deps: [build-cli]
    cmds:
      - chmod +x src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/pwnctl
      - mv src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/pwnctl ~/.local/bin
      - mkdir -p ~/.config/pwnctl/
      - chown $USER ~/.config/pwnctl/
      - mv src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/config.ini ~/.config/pwnctl/

  setup-ci:
    cmds:
      - gh variable set AWS_REGION --body "$(aws configure get region)"
      - gh variable set AWS_CALLER_IDENTITY --body "$(aws sts get-caller-identity | jq -r .Account)"
      - terraform -chdir=infra/modules/ci apply -auto-approve

  deploy:
    deps: [setup-ci, build-api, install-cli]
    cmds:
      - terraform -chdir=infra apply -auto-approve
      - ./bin/upload-conf.sh

  destroy:
    cmds:
      - ./bin/teardown.sh

  destroy-ci:
    cmds:
      - terraform -chdir=infra/modules/ci destroy

  debug-exec-long:
    cmds:
      - |
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-long") | .repositoryUri')
        latestTag=$(docker images | grep $ecrUri | head -n 1 | awk '{print $2}')
        aws ecr get-login-password --region $(aws configure get region) | docker login --username AWS --password-stdin $ecrUri
        docker run -v ~/.aws/:/root/.aws/ -e PWNCTL_USE_LOCAL_INTEGRATIONS=true \
                   -e PWNCTL_Logging__FilePath=/mnt/efs -e PWNCTL_Logging__MinLevel=Information \
                   -e PWNCTL_TaskQueue__VisibilityTimeout=1200 -e PWNCTL_OutputQueue__VisibilityTimeout=1200 \
                   -v "$(pwd)"/deployment:/mnt/efs -t ${ecrUri}:$latestTag

  debug-exec-short:
    cmds:
      - |
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-short") | .repositoryUri')
        latestTag=$(docker images | grep $ecrUri | head -n 1 | awk '{print $2}')
        aws ecr get-login-password --region $(aws configure get region) | docker login --username AWS --password-stdin $ecrUri
        docker run -e PWNCTL_USE_LOCAL_INTEGRATIONS=true \
                   -e PWNCTL_Logging__FilePath=/mnt/efs -e PWNCTL_Logging__MinLevel=Information \
                   -e PWNCTL_TaskQueue__VisibilityTimeout=1200 -e PWNCTL_OutputQueue__VisibilityTimeout=1200 \
                   -v "$(pwd)"/deployment:/mnt/efs -t ${ecrUri}:$latestTag

  debug-proc:
    cmds:
      - |
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-proc") | .repositoryUri')
        latestTag=$(docker images | grep $ecrUri | head -n 1 | awk '{print $2}')
        aws ecr get-login-password --region $(aws configure get region) | docker login --username AWS --password-stdin $ecrUri
        docker run -v ~/.aws/:/root/.aws/ -e PWNCTL_USE_LOCAL_INTEGRATIONS=true \
                   -e PWNCTL_Logging__FilePath=/mnt/efs -e PWNCTL_Logging__MinLevel=Information \
                   -e PWNCTL_TaskQueue__VisibilityTimeout=1200 -e PWNCTL_OutputQueue__VisibilityTimeout=1200 \
                   -v "$(pwd)"/deployment:/mnt/efs -t ${ecrUri}:$latestTag

  get-exec-logs:
    cmds:
      - awslogs get -s 1440m -G --timestamp /aws/ecs/exec

  get-proc-logs:
    cmds:
      - awslogs get -s 1440m -G --timestamp /aws/ecs/proc

  get-api-logs:
    cmds:
      - |
        functionName=$(aws lambda list-functions | jq -r '.Functions[] | select( .FunctionName | startswith("pwnctl_api") ) | .FunctionName')
        awslogs get -s 1440m -G --timestamp /aws/lambda/$functionName
