version: '3'

tasks:
  simple-setup: 
    deps: [install-deps, build-svc-image, push-svc-image, bootstrap-aws, deploy-app, install-cli, init-app]

  test:
    cmds:
      - dotnet test
  
  build-api:
    cmds:
      - dotnet clean
      - dotnet build src/pwnctl.api/pwnctl.api.csproj -c Release
  
  build-cli:
    cmds:
      - dotnet clean
      - dotnet publish src/pwnctl.cli/pwnctl.cli.csproj -c Release
  
  build-svc:
    cmds:
      - dotnet publish src/core/pwnctl.svc/pwnctl.svc.csproj -c Release

  build-svc-image:
    cmds:
      - docker build src/core/ -t public.ecr.aws/i0m2p7r6/pwnctl:latest

  push-svc-image:
    cmds:
      - |
        region=$(aws configure get region)
        aws ecr-public get-login-password --region $region \
          | docker login --username AWS --password-stdin public.ecr.aws/i0m2p7r6
        docker push public.ecr.aws/i0m2p7r6/pwnctl:latest
        
  build-all: 
    deps: [build-cli, build-api, build-svc-image]
    
  install-cli:
    deps: [build-cli]
    cmds:
      - chmod +x src/pwnctl.cli/bin/Release/net6.0/linux-x64/publish/pwnctl
      - sudo mv src/pwnctl.cli/bin/Release/net6.0/linux-x64/publish/pwnctl /usr/local/bin
      - sudo mkdir -p /etc/pwnctl/
      - sudo chown $USER /etc/pwnctl/
      - sudo mv src/pwnctl.cli/bin/Release/net6.0/linux-x64/publish/config.ini /etc/pwnctl/
      - sudo ./src/core/pwnctl.svc/scripts/get-psl.sh /etc/pwnctl/
      - sudo cp -r  ./src/core/pwnctl.infra/Persistence/seed /etc/pwnctl
  
  bootstrap-aws:
    cmds:
      - |
        region=$(aws configure get region)
        accountId=$(aws sts get-caller-identity --query "Account" --output text)
        cdk bootstrap aws://${accountId}/${region} -o src/core/pwnctl.infra.cdk/cdk.out

  deploy-app:
    deps: [clean-cdk, build-api, install-cli]
    cmds:
      - cdk deploy -o src/core/pwnctl.infra.cdk/cdk.out
      - chmod +x ./bin/*
      - ./bin/upload-conf.sh
      - ./bin/init-db.sh

  debug-svc:
    cmds:
      - |
        mkdir -p deployment/seed/
        cp ./src/core/pwnctl.infra/Persistence/seed/*.yml deployment/seed/
        docker run -e PWNCTL_TEST_RUN=true -e PWNCTL_INSTALL_PATH=/mnt/efs \
                   -e PWNCTL_Logging__FilePath=/mnt/efs -e PWNCTL_Logging__MinLevel=Debug \
                   -v "$(pwd)"/deployment:/mnt/efs -t public.ecr.aws/i0m2p7r6/pwnctl:latest

  clean-cdk:
    cmds:
      - rm -rf src/core/pwnctl.infra.cdk/cdk.out

  get-logs:
    cmds:
      - awslogs get -s 1440m -G --timestamp /aws/ecs/pwnctl

  destroy:
    cmds:
      - cdk destroy -o src/core/pwnctl.infra.cdk/cdk.out

  terraform:
    deps: [build-api, install-cli]
    cmds:
      - cd infra
      - echo yes | terraform apply
      - cd -

  install-deps:
    cmds:
      - |
        sudo apt-get install -y git curl wget jq docker nodejs
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
        unzip awscliv2.zip
        rm awscliv2.zip
        ./aws/install --update
        rm -rf ./aws
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash - 
        npm install -g aws-cdk
        curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel 6.0 -Runtime aspnetcore -InstallDir /usr/share/dotnet --architecture x64
        ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
        pip install awscurl
