version: '3'

tasks:
  test:
    deps: [test-unit, test-int]

  test-unit:
    cmds:
      - dotnet test --filter "FullyQualifiedName~test.unit"

  test-int:
    cmds:
      - |
        . ./bin/setenv.sh
        dotnet test --filter "FullyQualifiedName~test.int"
        docker-compose -f test/pwnctl.core.test.int/docker-compose.ecs-local.yml down

  build-api:
    cmds:
      - dotnet build src/pwnctl.api/pwnctl.api.csproj -c Release

  build-cli:
    cmds:
      - dotnet publish src/pwnctl.cli/pwnctl.cli.csproj -c Release

  build-exec-short-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-short") | .repositoryUri')
        docker build --build-arg COMMIT_HASH=$commitHash --ssh default=$SSH_AUTH_SOCK src/core/ -f src/core/pwnctl.exec/shortlived/Dockerfile -t ${ecrUri}:$commitHash
        docker tag ${ecrUri}:$commitHash ${ecrUri}:untested_$commitHash

  build-exec-long-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-long") | .repositoryUri')
        docker build --build-arg COMMIT_HASH=$commitHash --ssh default=$SSH_AUTH_SOCK src/core/ -f src/core/pwnctl.exec/longlived/Dockerfile -t ${ecrUri}:$commitHash
        docker tag ${ecrUri}:$commitHash ${ecrUri}:untested_$commitHash

  push-exec-short-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        region=$(aws configure get region)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-short") | .repositoryUri')
        docker push ${ecrUri}:$commitHash

  push-exec-long-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        region=$(aws configure get region)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-exec-long") | .repositoryUri')
        docker push ${ecrUri}:$commitHash

  build-proc-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-proc") | .repositoryUri')
        docker build --build-arg COMMIT_HASH=$commitHash src/core/ -f src/core/pwnctl.proc/Dockerfile -t ${ecrUri}:$commitHash
        docker tag ${ecrUri}:$commitHash ${ecrUri}:untested_$commitHash

  push-proc-image:
    cmds:
      - |
        commitHash=$(git rev-parse --short HEAD)
        region=$(aws configure get region)
        ecrUri=$(aws ecr describe-repositories | jq -r '.repositories[] | select( .repositoryName == "pwnctl-proc") | .repositoryUri')
        docker push ${ecrUri}:$commitHash

  build-all:
    deps: [build-cli, build-api, build-exec-short-image, build-exec-long-image, build-proc-image]

  install-cli:
    deps: [build-cli]
    cmds:
      - chmod +x src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/pwnctl
      - mv src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/pwnctl ~/.local/bin
      - mkdir -p ~/.config/pwnctl/
      - chown $USER ~/.config/pwnctl/
      - mv src/pwnctl.cli/bin/Release/net7.0/linux-x64/publish/config.ini ~/.config/pwnctl/

  setup-ci:
    cmds:
      #- ./bin/setup-gha-secrets.sh
      - terraform -chdir=infra/modules/ci apply -auto-approve

  deploy:
    deps: [build-api, install-cli]
    cmds:
      - terraform -chdir=infra apply -auto-approve
      - ./bin/upload-conf.sh

  destroy:
    cmds:
      - ./bin/teardown.sh

  destroy-ci:
    cmds:
      - terraform -chdir=infra/modules/ci destroy

  debug:
    cmds:
      - | 
        . ./bin/setenv.sh
        docker-compose -f test/pwnctl.core.test.int/docker-compose.ecs-local.yml up

  get-exec-logs:
    cmds:
      - awslogs get -s 1440m -G --timestamp /aws/ecs/exec

  get-proc-logs:
    cmds:
      - awslogs get -s 1440m -G --timestamp /aws/ecs/proc

  get-api-logs:
    cmds:
      - |
        functionName=$(aws lambda list-functions | jq -r '.Functions[] | select( .FunctionName | startswith("pwnctl_api") ) | .FunctionName')
        awslogs get -s 1440m -G --timestamp /aws/lambda/$functionName
