version: '3'

tasks:  
  bootstrap-cdk:
    cmds:
      - region=$(aws configure get region)
      - accountId=$(aws sts get-caller-identity --query "Account" --output text)
      - cdk bootstrap aws://${accountId}/${region} -o src/core/pwnctl.infra.cdk/cdk.out

  deploy-app-cdk:
    deps: [clean-cdk, build-api, install-cli]
    cmds:
      - cdk deploy -o src/core/pwnctl.infra.cdk/cdk.out
      - chmod +x ./bin/*
      - ./bin/upload-conf.sh

  destroy-cdk:
    cmds:
      - cdk destroy -o src/core/pwnctl.infra.cdk/cdk.out

  clean-cdk:
    cmds:
      - rm -rf src/core/pwnctl.infra.cdk/cdk.out
