#!/bin/bash

dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 20 -o /opt/dnsvalidator/resolvers.txt

head -25 /opt/dnsvalidator/resolvers.txt > /opt/resources/wordlists/dns/resolvers_top25.txt
