#!/bin/bash

if [ $# -eq 0 ]; 
then
    echo "USAGE: tld_scan <namefile> <tldfile>"
    exit 1
fi

for tld in $(cat $2)
do
	for name in $(cat $1)
    do
        dig +noquestion +nottlid $name.$tld | tr '\t' ' ' | grep "IN A"
    done
done