#!/bin/bash

sort_and_uniq() {
	cat $1 | sort | uniq > temp.txt
	cat temp.txt > $1
	rm temp.txt
}

DNS_RESOLVERS_FILE=/opt/dnsvalidator/resolvers_top25.txt
domain=$1

domainsfile=$(echo $domain)_domains.txt
httpfile=$(echo $domain)_http.txt
screenshotdir=$(echo $domain)_screenshots

cd /opt/pwntainer/data

mkdir $domain
cd $domain

datestamp=$(date +%Y%m%d)
mkdir $datestamp
cd $datestamp

echo "Scanning $domain"

#assetfinder -subs-only $domain | sort -u | tee $domainsfile
subfinder -silent -nC -o $domainsfile -rL $DNS_RESOLVERS_FILE -d $domain
subfinder_count=$(wc -l $domainsfile | awk '{print  $1}')

echo "subfinder found $subfinder_count subdomain(s)"

#/opt/massdns/scripts/subbrute.py -s 4000 /opt/massdns/lists/top200000.txt $domain | massdns --flush -r $DNS_RESOLVERS_FILE -t A -o J -w massdns.json
#echo "massdns found $(wc -l massdns.json | awk '{print  $1}') subdomains"
#TODO: append massdns findings to domains file & uniq

amass enum -rf $DNS_RESOLVERS_FILE -max-dns-queries 20000 -d $domain -dir . -active | tee -a $domainsfile
cat $domainsfile | unfurl --unique domains | grep $domain > tmpfile
cat tmpfile > $domainsfile
rm tmpfile

amass_count=$(wc -l $domainsfile | awk '{print  $1}')
amass_count=$(($amass_count-$subfinder_count))

echo "amass found $amass_count new subdomains"

dig_deep $domainsfile
if ! [ -s all_records.txt ]
then
	cat all_records.txt | awk '{print $4}' | tee -a $domainsfile
	sort_and_uniq $domainsfile
fi

cat $domainsfile | httpx -silent -ports 80,443,8080,8443 | tee -a $httpfile
echo "$(wc -l $httpfile | awk '{print  $1}') web servers found."

cat $domainsfile | aar
cat $httpfile | aar

echo "Taking screenshots.."

cat $httpfile | aquatone -chrome-path /usr/bin/chromium-browser -http-timeout 6000 -scan-timeout 400 -screenshot-timeout 300000 -out $screenshotdir
