#!/bin/bash

while (( "$#" )); do
	case "$1" in
    	-t|--target)
			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        		TARGET=$2
        		shift 2
      		else
        		echo "Error: Argument for $1 is missing" >&2
        		exit 1
      		fi
      	;;
		-f|--file)
      		if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        		TARGET_FILE=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
		;;
		-p|--ports)
			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
				ADDITIONAL_PORTS=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
		;;
		-*|--*=) # unsupported flags
				echo "Error: Unsupported flag $1" >&2
			exit 1
		;;
	esac
done

scan_target() {
	escaped_cidr=$(echo $1 | tr '/' '_')
	hostsfile=$(echo $escaped_cidr)_hosts.txt
	masscanfile=$(echo $escaped_cidr)_masscan.json
	nmapoutfile=$(echo $escaped_cidr)_nmap.xml
	
	cd /opt/pwntainer/data
	
	mkdir $escaped_cidr 2>/dev/null
	cd $escaped_cidr

	datestamp=$(date +%Y%m%d)
	mkdir $datestamp 2>/dev/null
	cd $datestamp

	sudo masscan $ports $1 -oD $masscanfile

	cat $masscanfile | jq .ip -r | sort -u > $hostsfile
	host_count=$(wc -l $hostsfile | awk '{print $1}')
	echo "masscan found $host_count host(s)"

	if [[ $host_count > 0 ]]
	then
		ports=$(cat $masscanfile | jq .port | sort -u | tr '\n' ',')
		ports=${ports::-1}

		sudo nmap -O -sSVC -p $ports -iL $hostsfile -oX $nmapoutfile --webxml
	fi

	rm $hostsfile
}

if [[ -z $TARGET && -z $TARGET_FILE ]];
then
    echo "USAGE: scan [-t <cidr_or_ip>|-f <targets_file>] [-p <additional_ports>]"
	echo "No targets provided" >&2
    exit 1
fi

ports=-p21,22,23,80,81,139,443,445,995,1433,1723,2075,2076,2083,2375,3000,3306,3868,4443,5380,5443,5900,6443,7443,8069,8080,8880,1900,8443,9000,9091,9200,9443,10000,10250

echo "Default Ports: $ports"
if [[ $ADDITIONAL_PORTS ]]
then
	echo "Additional Ports: $ADDITIONAL_PORTS"
	ports=$ports,$ADDITIONAL_PORTS
fi

if [ -n $TARGET ];
then
	scan_target $TARGET
else
	for target in $(cat $TARGET_FILE)
	do
		scan_target $target
		cd ../..
	done
fi

cat $hostsfile | aar
cat $masscanfile | jq -r '[.ip, .port] | "\(.[0]):\(.[1])"' | aar