#!/bin/bash

sort_and_uniq() {
	cat $1 | sort -u > temp.txt
	cat temp.txt > $1
	rm temp.txt
}

DNS_RESOLVERS_FILE=/opt/wordlists/dns/resolvers_top25.txt
domain=$1

domainsfile=subdomains.txt
baseurlfile=baseurls.txt

cd /opt/pwntainer/data

mkdir $domain 2>/dev/null
cd $domain

datestamp=$(date +"%Y-%m-%d")
mkdir $datestamp 2>/dev/null
cd $datestamp

#assetfinder -subs-only $domain | sort -u | tee $domainsfile
subfinder -silent -nC -o $domainsfile -rL $DNS_RESOLVERS_FILE -d $domain

shuffledns -d $domain -w /opt/pwntainer/wordlists/top20000.txt -r $DNS_RESOLVERS_FILE -strict-wildcard -silent -o shuffledns.txt
cat shuffledns.txt >> $domainsfile
sort_and_uniq $domainsfile

amass enum -rf $DNS_RESOLVERS_FILE -max-dns-queries 20000 -d $domain -dir . -nolocaldb -noalts -nocolor -active | tee -a $domainsfile
cat $domainsfile | unfurl --unique domains | grep $domain > tmpfile
cat tmpfile > $domainsfile
rm tmpfile

dig_deep $domainsfile $domain
if ! [ -s all_records.txt ]
then
	cat all_records.txt | grep CNAME | awk '{print $4}' | tee -a $domainsfile
	sort_and_uniq $domainsfile
fi

cat resolvable_domains.txt | httpx -silent -ports 80,443,8080,8443 | tee -a $baseurlfile

waybackrecon () {
	mkdir ./wayback-data/ 2>/dev/null

	cat $baseurlfile | waybackurls > ./wayback-data/waybackurls.txt
	cat ./wayback-data/waybackurls.txt  | sort -u | unfurl --unique keys > ./wayback-data/paramlist.txt
	cat ./wayback-data/waybackurls.txt  | sort -u | grep -P "\w+\.js(\?|$)" | sort -u > ./wayback-data/jsurls.txt
	cat ./wayback-data/waybackurls.txt  | sort -u | grep -P "\w+\.php(\?|$) | sort -u " > ./wayback-data/phpurls.txt
	cat ./wayback-data/waybackurls.txt  | sort -u | grep -P "\w+\.aspx(\?|$) | sort -u " > ./wayback-data/aspxurls.txt
	cat ./wayback-data/waybackurls.txt  | sort -u | grep -P "\w+\.jsp(\?|$) | sort -u " > ./wayback-data/jspurls.txt
}

waybackrecon $domain

cat $baseurlfile | aquatone -chrome-path /usr/bin/chromium-browser -silent -threads=5 -screenshot-timeout 300000