version: '3.4'

services:
  pwntainer:
    image: aristosmiliaressis/pwnctl:latest
    container_name: pwntainer
    hostname: pwntainer
    network_mode: host
    environment:
      - PWNCTL_JobQueue:WorkerCount=1
      - PWNCTL_Db:ConnectionString=Host=my_host;Database=my_db;Username=my_user;Password=my_pw
    restart: unless-stopped
    volumes:
      - ./data/:/etc/pwnctl/
