version: '3.4'

services:
  pwnctl:
    image: aristosmiliaressis/pwnctl:latest
    container_name: pwnctl
    hostname: pwnctl
    network_mode: host
    environment:
      - PWNCTL_JobQueue__WorkerCount=1
      - PWNCTL_Db__ConnectionString=Host=my_host;Database=my_db;Username=my_user;Password=my_pw
    restart: unless-stopped
    volumes:
      - ./data/:/etc/pwnctl/
