name: ci

on:
  push:
    branches:
      - '**'
  pull_request:

  workflow_dispatch:

jobs:
  test-and-build-cli:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v2

      - name: Cache Nuget packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget

      - name: test cli
        run: dotnet test

      - name: build cli
        run: dotnet publish "src/pwnctl.cli/pwnctl.cli.csproj" -c Release -o ./build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: ./build/pwnctl
          retention-days: 1

  release-cli:
    needs: test-and-build-cli
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: executable

      - name: get datetime stamp
        run: echo "::set-output name=STAMP::$(date +%y%m%d%H%M%S)"
        id: datetime

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}.${{ steps.datetime.outputs.STAMP }}
          release_name: Release ${{ github.run_number }}.${{ steps.datetime.outputs.STAMP }}

      - name: Upload relase assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: pwnctl
          asset_path: ./pwnctl
          asset_content_type: application/x-elf

  build-and-push-worker:
    needs: test-and-build-cli
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout subject branch
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: aristosmiliaressis/pwnctl:latest
          context: src/pwnctl.worker
          cache-from: type=gha
          cache-to: type=gha,mode=max
