name: ci

on:
  push:
    branches:
      - '**'
  pull_request:

  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Cache Nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget

      - name: Run Unit Tests
        run: dotnet test --filter "FullyQualifiedName~test.unit"

  build-cli:
    needs: unit-test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Cache Nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget

      - name: build cli
        run: dotnet publish "src/pwnctl.cli/pwnctl.cli.csproj" -c Release -o ./pwnctl

  build-api:
    needs: unit-test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Cache Nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget

      - name: build api
        run: dotnet build src/pwnctl.api/pwnctl.api.csproj

  build-worker-img:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_CALLER_IDENTITY }}:role/GitHubAction-AssumeRoleWithAction
          aws-region:  ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build worker image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.login-ecr.outputs.registry }}/pwnctl:untested
          push: true
          context: src/core/
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-worker-img:
    needs: build-worker-img
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
      volumes:
        - /tmp/:/__w/pwnctl/
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Cache Nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget

      - name: Test worker image
        run: |
          export ECR_REGISTRY_URI=${{ vars.AWS_CALLER_IDENTITY }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/pwnctl
          dotnet test --filter "FullyQualifiedName~pwnctl.svc"

  push-wroker-img:
    needs: test-worker-img
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_CALLER_IDENTITY }}:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull untested image
        run: docker pull ${{ steps.login-ecr.outputs.registry }}/pwnctl:untested

      - name: Retag image from untested to latest
        run: docker buildx imagetools create -t ${{ steps.login-ecr.outputs.registry }}/pwnctl:latest${{ steps.login-ecr.outputs.registry }}/pwnctl:untested
