name: pwnwrk-ci

on:
  push:
    branches:
      - '**'
  pull_request:

  workflow_dispatch:

jobs:
  test-cli:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Cache Nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: nuget

      - name: test cli
        run: dotnet test

  build-and-push-worker:
    needs: test-cli
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout subject branch
        uses: actions/checkout@v3

      - name: Login to Public ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: public.ecr.aws/i0m2p7r6/pwnwrk:latest
          context: src/
          cache-from: type=gha
          cache-to: type=gha,mode=max
