name: tests

on:
  push:
    branches:
      - '**'
  pull_request:

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subject branch
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
            dotnet-version: 6.0

      - name: run tests
        run: dotnet test